# -*- coding: utf-8 -*-
"""Assignment-1 (PoliceKillingUS-Matplotlib) student.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu6bGU6TCzC0NDASYTjL-lZz1Mi1OR28

# WITH PANDAS AND MATPLOTLIB
"""

import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

"""INSTRUCTIONS

1. Number of people by gender
1. Kill weapon
1. Age of killed people
1. Race of killed people
1. Killed People According to Races (Pie Chart)
1. Most common 15 Name or Surname of killed people

<br>

read data

if didn't work you can use this parameters: encoding="windows-1252"
"""

kill = pd.read_csv('/PoliceKillingsUS.csv', encoding="windows-1252")

from google.colab import drive
drive.mount('/content/drive')

"""## 1: Plot number of people by gender"""

kill.head()

# with matplotlib
fig,ax = plt.subplots()
ax.bar(kill.gender.value_counts().index, kill.gender.value_counts().values)
ax.set_title("Gender Distribution")

"""## 2: Plot 7 most common kill weapons"""

a = kill.groupby("armed")["armed"].count().sort_values(ascending=False).head(7)
a

# with matplotlib
fig,ax = plt.subplots()
ax.bar(a.index, a.values)

plt.xticks(rotation = 45);

"""## 3: Plot number of age of killed people under two groups : Under 25 and Above 25"""

kill.head()

above_25 = kill.age >25
below_25 = kill.age <25

kill_above_25 = kill[kill.age>25]
kill_below_25 = kill[~(kill.age>25)]
above_25 = len(kill_above_25)
below_25 = len(kill_below_25)
below_25





print("above25  :",above_25)
print("below25  :",below_25)

plt.bar(["above_25","below_25"],[above_25,below_25])

# with matplotlib

"""## 4: Plot number of killed poeple by race"""

kill.race.value_counts()



plt.bar(kill.race.value_counts().index,kill.race.value_counts().values)
plt.title("Race of Killed People", color="blue");

# with matplotlib



"""## 5: Killed People According to Races (Pie Chart)"""

kill.head()



kill.race.unique()

kill.race.value_counts()



"""Problem: missing value on race column.

**INSTRUCTION-1: Drop the all raws that contain missing value (dropna)**
"""

kill2 = kill.dropna()
kill2

kill2.shape



"""**INSTRUCTION-2: Demonstrate Race Ratio of Killed People by a Pie Chart (You can use Matplotlib)**"""

kill2.race.value_counts()



etiket = kill2.race.value_counts().index
etiket



deger = kill2.race.value_counts().values
deger



plt.pie(deger,labels = etiket );
plt.legend()
plt.show()

# matplotlib

